M48
; DRILL file {KiCad 9.0.1} date 2026-04-13T18:53:09-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-13T18:53:09-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X5.1618Y-1.0669
X5.3894Y-1.0669
T2
X4.06Y-0.84
X4.06Y-4.98
X7.9Y-0.82
X7.9Y-4.98
M30
