M48
; DRILL file KiCad 10.0.5 date 2026-09-04T15:37:05
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-09-04T15:37:05-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X3.7786Y-3.1157
X4.0061Y-3.1157
T2
X1.5Y-3.16
X1.5Y-4.47
X5.9154Y-3.166
X5.9154Y-4.4685
M30
