(part "L7805CV"
    (packageRef "TO255P460X1020X2008-3P")
    (interface
        (port "1" (symbPinId 1) (portName "INPUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GROUND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "OUTPUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "L7805CV")
    (property "Mouser_Part_Number" "511-L7805CV")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/L7805CV?qs=9NrABl3fj%2FqplZAHiYUxWg%3D%3D")
    (property "Arrow_Part_Number" "L7805CV")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/l7805cv/stmicroelectronics.html?utm_currency=USD&region=europe")
    (property "Description" "Linear voltage regulator,L7805CV 5V 1.5A STMicroelectronics L7805CV, Single Linear Voltage Regulator, 1.5A 5 V, 3-Pin TO-220")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/l78.pdf")
    (property "symbolName1" "L7805CV")
)
